### ISSUE TITLE
Error compiling with gcc-10.1.0

### ISSUE THREAD

**Issue by cjain7** [ekg/mutatrix#3]
Hi Erik,

In order to compile mutatrix, I had to change two lines in `vcflib/fsom/fsom.c` to avoid a compiler error. The change made is following:

OLD: `dist_i = abs(x - i) ;`
NEW: `dist_i = abs( static_cast<int>(x - i) );`

Why an error occurred and change was needed is explained here: https://stackoverflow.com/a/50301673

**Comment by ekg** [comment]
Hi Chirag,

Thanks for the note. I think I can probably update vcflib to make this work.

The irony is that mutatrix shouldn't really have need of that code. It's a
lesson in dependency risk.

Erik

**Comment by ekg** [comment]
Sorry it's taken a while to get back to this. Working on alignment evaluations has led me back to mutatrix.

I've updated the master to use a new vcflib. This problem seems to have been resolved in vcflib development over the years.

Hope it's still helpful!
